# Generated by Django 5.1.3 on 2025-11-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
